name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: "Deploy to server"
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p /home/runner/.ssh/
          echo "$SSH_PRIVATE_KEY" > /home/runner/.ssh/deploy-key.pem
          chmod 600 /home/runner/.ssh/deploy-key.pem
          cat >> /home/runner/.ssh/config <<END
          Host my-server
            HostName $SSH_IP
            User $SSH_USER
            IdentityFile /home/runner/.ssh/deploy-key.pem
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_IP: ${{ secrets.SSH_IP }}

      - name: Deploy site
        run: ssh my-server
          'systemctl restart mongowheels.service &&
          systemctl status mongowheels.service'

    notify:
      needs: deploy
      name: "Notify on Discord"
      runs-on: ubuntu-latest
      if: ${{ always() }}
      steps:
        - name: Success Notification
          if: ${{ needs.deploy.result == 'success' }}
          run: curl -s -X POST "${{ secrets.DISCORD_WEBHOOK }}" -d "content=🚀 Deployment Successful"
        - name: Error Notification
          if: ${{ needs.deploy.result == 'failure' }}
          run: curl -s -X POST "${{ secrets.DISCORD_WEBHOOK }}" -d "content=Deployment Error :("
